### ISSUE TITLE
proper management of files

### ISSUE THREAD

**Issue by Anuraj-IND** [GFGVITAP/DSAin100days#68]
e.g 
folder name :- singly linkedlist
menu driven program of singly linked list
some questions on it to boost the over all learning experience 
if its fine assign me this issue and labels hacktoberfest gssoc

**Comment by Anuraj-IND** [comment]
@Rohith2201 hello respond to it please

**Comment by Anuraj-IND** [comment]
Bro after assigning you don't close issue before it's done aio 😭 reopen it and wait for me to work on it

**Comment by Anuraj-IND** [comment]
@Rohith2201 check pull request and review it i ran it on an online compiler it was working fine you can now accept the pull request

**Comment by monish-parimi** [comment]
@Anuraj-IND I guess @Rohith2201 has already assigned you hacktoberfest label for the work that you have contributed and closed the pull request previously.

So what is your issue exactly ?

**Comment by Anuraj-IND** [comment]
> @Anuraj-IND I guess @Rohith2201 has already assigned you hacktoberfest label for the work that you have contributed and closed the pull request previously.
> 
> So what is your issue exactly ?

You're responding to old issue ig
