### ISSUE TITLE
Insertion and Deletion in singly linked list through Python

### ISSUE THREAD

**Issue by Arisha2902** [GFGVITAP/DSAin100days#78]
Insertion and deletion at beginning ,end and index position in singly linked list, through python.

**Comment by Anuraj-IND** [comment]
@Rohith2201 sir please check it and accept the pull we need some more pull accept please be active here once more till the end of october shes someone ik its her first open src contribution just like me so help us please :) and respond us when ASAP

**Comment by Anuraj-IND** [comment]
@Rohith2201 sir let us complete it first then close the issue after finalizing the pull request btw thanks for letting us contribute here
