### ISSUE TITLE
Insertion and Deletion in "Doubly and Circular Linked List" through Python

### ISSUE THREAD

**Issue by Arisha2902** [GFGVITAP/DSAin100days#79]
Insertion and Deletion at beginning ,end and index position in Doubly and Circular Linked List, through python

**Comment by Anuraj-IND** [comment]
@Rohith2201 sir please check it and accept the pull we need some more pull accept please be active here once more till the end of october shes someone ik its her first open src contribution just like me so help us please :) and respond us when ASAP
