### ISSUE TITLE
3D ARRAYS in PYTHON 

### ISSUE THREAD

**Issue by Anuraj-IND** [GFGVITAP/DSAin100days#81]
@Rohith2201 im added 3D array handling through python here coz python file still looks very empty and 3D array handling is something unique to so why not please assign me this and add labels thanks

**Comment by Anuraj-IND** [comment]
i actually need one more contribution to complete my goal so please help me out here @Rohith2201

**Comment by Rohith2201** [comment]
@Anuraj-IND make a pull request

**Comment by Anuraj-IND** [comment]
@Rohith2201 i already sent pull request too

**Comment by Anuraj-IND** [comment]
> @Anuraj-IND make a pull request

already did see
